sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        OcDR9eASYwqfOisPQhEpUt4Bm396zpBhpuOdkpj+KAWOxp9rzh9oZCMrwzK5q1gZ+x6eQAUueBGggkOR8rhENBOHyu/iVopEeq3CTrLs1IGp/iqvB/X5FZ4IFb0MpTh0mMEjHeXogg58DJHfAdOX0lKei44uXQQAmryD+o5Gv7C6nz5b3CAqogFkls8K6gthFEGZ8Ef848aYZVCcbThYzvx+8amh1T0tZYcmcY6Qdz9YLdJzg/5jPB/cYttRtIzc6acepsU5uLUawn63nsM2Un1rVJiAzdP5phh2qtdkwfEB2OXQfdeMOksOksDTfkl3C2JhDoIkbeBODhqZFctExlp88t0j+TGkBehH0Gk+ocvlJvG5qJz90xTx3rXbyRQkJLADFplSRtfTX3ohM8OWGKPmrRSz3/1qvJDZq7dD4sfOeos266r2n8VMQA1aMS6mYkIl38c2WVdYsJpdssKLIeh4O2eHyQOCYn1VsSoEXF/k9ZnaBLwMThDU24VsqY+FPwPZGLoyW+QOJEXHFxbcY31UXXNSQ5Y14adNXTTjJbe4QA9+HU9oiccVJjeBRVNHNQgq8bT9Ce9IQ3IBDvxWv3pPMIpLh6CaJ1IqWcBgatm+7iGaky6yP6noZJu+TmGPjZSkm4UbhfNFY4f9BjHg6hOH2ypTC7iIgfHXXJgL39Q=
    - secure: >-
        BGTrQSWSaTqMliBljmy6Uy2jtP8kzw48n6c6hW6zihZkHA65sIUGBjvmnP/HBYkn1wSovNvejcRU8/GU7PBi3ZxhRqCoZuI3Gfxz3zXLRqnxCy3bEBjKVqG3cXcpLDvYqFDDW9uYNe4NbRHkqPgQeJjvjidgWSBX41JHEdwAr00H4fjMjxjueO/T+1dIegWRkhET85tndNO4XAPVGOhMUhQcp18xK+jYJCbPgTAHi6YyR1x2k7v7Duw9UlAf3g8GmTLs41mY71VB8zXonJcIUVaXbTo1e6oxEzDBIK2HcjueWjWRFe7n87oKFhl4d27YFNRVR0gsPss5VHz7CD5SBaXGBk9Jt0e2NFSGw8qp99TNSRHhrl1n9+Mp6Z20tz4AyZmwo3t7vtav8LFQNy21piC5kxVoV/c5AXDvZ2kNYpX/bKq336Mjj3xI+/smF6ILgNIvgCmBWWFVLfMv2ONkTnrXw6w4KGM/pBEUOGj1+K0+uTwrisng6IZ35xZsMTizxhM5p2stBxQgQ+syuWlI1W7+O9G4EgCX32s4hZkekoBkAgtwQG9xFhEuV0DWv2bFW3Zx5tnsTnEmzA95N/E8qmUBi2JKoylpVcOGIoRw1cvexthQvFx5q3vhtAlBZFLHC2zmbYNT5cDSi9/o1e8TdZYcot93B9WhtqWiWSboBWA=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
